### ISSUE TITLE
Map format - Music

### ISSUE THREAD

**Issue by ghost** [GlPortal/specification#1]
Map format should support to set specific track / music file for current map.
### Implementation 1

``` xml
<music track="name" />
```
### Implementation 2

``` xml
<music>
  <track>name1</track>
  <track>name2</track>
</music>
```

**Comment by hhirsch** [comment]
We also need a new trigger type to toggle tracks.

**Comment by ghost** [comment]
@hhirsch good idea with trigger....

**Comment by hhirsch** [comment]
I close this for now. I think the trigger spec. covers it with the music trigger.
