### ISSUE TITLE
Add screen trigger

### ISSUE THREAD

**Issue by ghost** [GlPortal/specification#5]
Do we need it or should it be replaced with script trigger ?
Some solution is required in order to remove '<end>' from maps

**Comment by hhirsch** [comment]
@SGOrava Screen triggers are still relevant for two reasons:
1. Script triggers will take some time to implement while screen triggers are implemented in a short amount of time. This is especially significant giving our limited resources atm.
2. Even after we have script triggers implemented the screen triggers might be a simpler way to trigger screens than script triggers.

I am closing this for now but if we should talk about this more please re-open it.

CC @Geertiebear
